# -*- coding: utf-8 -*-
"""Birthweight_Reduced

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWqS4yn9VLBwBeP8adaObFsBgb-Y-J67
"""

#Nomes: João Victor Fernandes   RA: 231024967
#       Vinicius H. O. Franzote RA: 221024174

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
from google.colab import files

#Carregando arquivos
uploaded = files.upload()

file = 'Birthweight_reduced_kg_R.csv'

dados = pd.read_csv(file)

dados.head()

#Histograma

#acessando valores de um atributo
peso = dados['Birthweight']

# acessando valores de um atributo
tamanho = dados['Length']

#Peso do bebê
sb.displot(peso, kde=True)
plt.title('Histograma do Peso do Bebê')
plt.xlabel('Peso do Bebê')
plt.ylabel('Frequência')
plt.show()

#Altura do bebê
sb.displot(tamanho, kde=True)
plt.title('Histograma da Altura do Bebê')
plt.xlabel('Altura do Bebê')
plt.ylabel('Frequência')
plt.show()

# Mães fumantes e não fumantes

import matplotlib.pyplot as plt

# Contando o número de mães fumantes e não fumantes
num_fumantes = dados[dados['smoker'] == 1].shape[0]
num_nosmokers = dados[dados['smoker'] == 0].shape[0]

# Dados para o gráfico de pizza ou pie
labels = ['Fumantes', 'Não Fumantes']
sizes = [num_fumantes, num_nosmokers]
colors = ['#f70c1c','#66b3ff']

# Criando o gráfico de pizza ou pie
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.title('Distribuição de Mães Fumantes e Não Fumantes')
plt.axis('equal')  # Equaliza para garantir que o gráfico seja um círculo
plt.show()

# Média, mediana, moda e desvio padrão da altura e tempo de gestação de bebês

#Altura

#média e desvio padrão
dados['Length'].describe()

#mediana
dados['Length'].median()

#moda
dados['Length'].mode()

#Tempo de Gestação

#média e desvio padrão

dados['Gestation'].describe()

#mediana
dados['Gestation'].median()

#moda
dados['Gestation'].mode()

# Boxplot: idade da mãe e idade do pai
plt.figure(figsize=(10, 6))
plt.boxplot([dados['mage'], dados['fage']], labels=['Idade da Mãe', 'Idade do Pai'])
plt.title('Boxplot das Idades da Mãe e do Pai')
plt.ylabel('Idade')
plt.show()

# Gráfico de dispersão do peso do bebê e do tempo de gestação
plt.figure(figsize=(10, 6))
sb.scatterplot(data=dados, x='Gestation', y='Birthweight', hue='smoker', palette={1: 'orange', 0: 'blue'})
plt.title('Dispersão do Peso do Bebê vs Tempo de Gestação')
plt.xlabel('Tempo de Gestação (semanas)')
plt.ylabel('Peso do Bebê (gramas)')
ax = plt.gca()
handles, labels = ax.get_legend_handles_labels()
new_labels = ['Não', 'Sim']
plt.legend(handles=handles, labels=new_labels, title='Fumante')
plt.legend(handles=handles, labels=new_labels, title='Fumante', loc='upper left')
plt.show()

# Separando os dados em fumantes e não fumantes
fumante = dados[dados['smoker'] == 1]
nao_fumante = dados[dados['smoker'] == 0]

# Calculando a linha de regressão para fumantes
coef_fumante = np.polyfit(fumante['Gestation'], fumante['Birthweight'], 1)
poly1d_fn_fumante = np.poly1d(coef_fumante)

# Calculando a linha de regressão para não fumantes
coef_nao_fumante = np.polyfit(nao_fumante['Gestation'], nao_fumante['Birthweight'], 1)
poly1d_fn_nao_fumante = np.poly1d(coef_nao_fumante)

# Criando o gráfico de dispersão
plt.figure(figsize=(10, 6))
sb.scatterplot(data=dados, x='Gestation', y='Birthweight', hue='smoker', palette={1: 'orange', 0: 'blue'})
plt.title('Peso do Bebê vs Tempo de Gestação com Status de Fumante')
plt.xlabel('Tempo de Gestação (semanas)')
plt.ylabel('Peso do Bebê (gramas)')

# Adicionando as linhas de regressão
plt.plot(fumante['Gestation'], poly1d_fn_fumante(fumante['Gestation']), color='orange', label='Fumante (1)')
plt.plot(nao_fumante['Gestation'], poly1d_fn_nao_fumante(nao_fumante['Gestation']), color='blue', label='Não Fumante (0)')

# Adicionando a legenda
plt.legend(title='Status de Fumante')
plt.show()

dados['smoker'] = dados['smoker'].astype(str)

# Criando o box plot
plt.figure(figsize=(8, 6))
sb.boxplot(x='smoker', y='Birthweight', data=dados, hue='smoker', dodge=False)
plt.title('Box Plot do Peso do Bebê ao Nascer em Função do Status de Fumante')
plt.xlabel('Fumante')
plt.ylabel('Peso do Bebê (gramas)')
plt.xticks(ticks=[0, 1], labels=['Não', 'Sim'])
plt.show()

"""A normalidade das distribuições dos histogramas sugere padrões previsíveis de crescimento intrauterino. No entanto, a variabilidade observada, especialmente nos pesos mais baixos, pode estar associada a fatores de risco, como o tabagismo materno.

O estudo da amostra é praticamente nivelado entre mães fumantes e não fumantes, permitindo uma comparação equilibrada entre os grupos.

Os gráficos fornecem evidências de uma correlação entre o tabagismo durante a gravidez e o peso ao nascer dos bebês. Especificamente, o tabagismo materno está associado a um menor peso ao nascer, uma tendência evidente tanto nos gráficos de dispersão quanto nos boxplots, onde os bebês de mães fumantes tendem a ter pesos menores em diferentes durações de gestação.

Além disso, o boxplot revela que, embora as medianas dos pesos ao nascer para bebês de mães fumantes e não fumantes sejam relativamente próximas, há uma maior variabilidade no peso dos bebês de mães fumantes. Isso sugere que o tabagismo contribui para uma maior incerteza no peso ao nascer, aumentando o risco de bebês nascerem com pesos extremamente baixos.

Além disso, a análise das idades médias dos pais e das mães indica uma diferença perceptível, com os pais tendendo a ser mais velhos que as mães. Essa disparidade pode refletir diferentes padrões de comportamento ou fatores sociais que influenciam a gravidez e o tabagismo.
"""