# -*- coding: utf-8 -*-
"""Sistemas para tomada de decisão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHjHM5IekL5wDvM5oNyoFMtJErEYK8M-
"""



"""Kevin André Garcia Duarte          RA: 221025324

Vinicius Henrique de Oliveira Franzote      RA: 221024174
"""

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
from google.colab import files

#Carregando arquivos
uploaded = files.upload()

file = '4747-esi-semana-08-idh-censo-sao-paulo-1991-2010.csv'

dados = pd.read_csv(file)

dados.head()

#Evolução de três cidades

# Dados
data = {
    'Localidade': ['Bauru', 'Barretos', 'Santos', 'Bauru', 'Barretos', 'Santos', 'Bauru', 'Barretos', 'Santos'],
    'idh1991': [0.607, 0.558, 0.689, None, None, None, None, None, None],
    'idh2000': [None, None, None, 0.736, 0.710, 0.785, None, None, None],
    'idh2010': [None, None, None, None, None, None, 0.801, 0.789, 0.840]
}
df = pd.DataFrame(data)

# Filtrando as cidades desejadas
cidades = ['Bauru', 'Barretos', 'Santos']
df_cidades = df[df['Localidade'].isin(cidades)]

# Transformando o DataFrame para formato longo
df_long = df_cidades.melt(id_vars='Localidade',
                          value_vars=['idh1991', 'idh2000', 'idh2010'],
                          var_name='Ano', value_name='IDH')

# Ajustando a coluna 'Ano' para ficar apenas com os anos (remover 'idh')
df_long['Ano'] = df_long['Ano'].str.extract('(\d+)')

# Remover valores nulos, se houver
df_long.dropna(inplace=True)

# Criando o gráfico com matplotlib
plt.figure(figsize=(10, 6))

# Loop para plotar cada cidade
for cidade in cidades:
    df_cidade = df_long[df_long['Localidade'] == cidade]
    plt.plot(df_cidade['Ano'], df_cidade['IDH'], marker='o', label=cidade)

# Configurações do gráfico
plt.title('Evolução do IDH das Cidades')
plt.xlabel('Ano')
plt.ylabel('IDH')
plt.legend(title='Localidade')
plt.grid(True)
plt.show()

# Filtrando apenas a cidade de São Paulo
dados_sao_paulo = dados[dados['Localidade'] == 'São Paulo']

# Calculando média, moda e mediana dos índices de IDH para São Paulo

# Média
media_sao_paulo = dados_sao_paulo[['idh1991', 'idh2000', 'idh2010']].mean()
print("Média dos IDHs de São Paulo:")
print(media_sao_paulo)

# Mediana
mediana_sao_paulo = dados_sao_paulo[['idh1991', 'idh2000', 'idh2010']].median()
print("\nMediana dos IDHs de São Paulo:")
print(mediana_sao_paulo)

# Moda
moda_sao_paulo = dados_sao_paulo[['idh1991', 'idh2000', 'idh2010']].mode()
print("\nModa dos IDHs de São Paulo:")
print(moda_sao_paulo)

# Calculando média, moda e mediana dos índices de IDH por porte

# Agrupando os dados por porte e calculando a média
media_por_porte = dados.groupby('porte')[['idh1991', 'idh2000', 'idh2010']].mean()
print("Média dos IDHs por porte:")
print(media_por_porte)

# Agrupando os dados por porte e calculando a mediana
mediana_por_porte = dados.groupby('porte')[['idh1991', 'idh2000', 'idh2010']].median()
print("\nMediana dos IDHs por porte:")
print(mediana_por_porte)

# Agrupando os dados por porte e calculando a moda
moda_por_porte = dados.groupby('porte')[['idh1991', 'idh2000', 'idh2010']].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
print("\nModa dos IDHs por porte:")
print(moda_por_porte)



"""4 - Há alguma tendência do crescimento ou diminuição do IDH das cidades de acordo com seu porte?

Há uma tendência de crescimento do IDH em todas as categorias de porte, mas o crescimento é mais acelerado em cidades de maior porte (Metrópole e Grande).

"""



"""5 - Há alguma relação entre o tamanho da população e o IDH?

O tamanho da população pode ter um impacto nos fatores que compõem o IDH, como saúde, educação e renda, ele não é o único determinante. Políticas governamentais, distribuição de recursos e outros fatores socioeconômicos desempenham papéis cruciais nessa relação.

6 - Com base nas análises realizadas, o que pode ser feito pelo governo do estado para melhorar o IDH das cidades?

Para melhorar o IDH das cidades, o governo estadual deve focar em educação, saúde e renda. Na educação, é importante investir em infraestrutura escolar, valorizar professores e usar tecnologias educacionais. Na saúde, ampliar o atendimento, fortalecer a prevenção e capacitar profissionais são essenciais. Programas sociais e desenvolvimento regional equilibrado ajudam a reduzir desigualdades. Além disso, é crucial uma gestão eficiente, com monitoramento das políticas e participação da comunidade.
"""