# -*- coding: utf-8 -*-
"""Uso de internet no mundo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pYsV4vzxsyVwgxhFsaccBiTfpY1bw7p

**Roberto Prado                                                  RA 221022157**
**Vinicius Henrique de Oliveira Franzote                         RA 221024174**
"""

#visualização de dados
import seaborn as sns
#ciência de dados
import pandas as pd
#mapas e geolocalização
import geopandas as gpd
import folium
#manipulação de arquivos json
import json

#carregando arquivos do PC
from google.colab import files
uploaded = files.upload()

file = '4747-esi-semana-10-usuarios-por-pais-1990-2017.csv'

dados = pd.read_csv(file)

dados.head()

import matplotlib.pyplot as plt
# Verificar os nomes das colunas para garantir que estão corretos
print(dados.columns)

# Criar o gráfico de evolução do uso da internet ao longo dos anos
plt.figure(figsize=(10,6))
plt.plot(dados['Year'], dados['Users'], marker='o', linestyle='-', color='r')

# Adicionar título e rótulos aos eixos
plt.title('Evolução do Uso da Internet ao Longo dos Anos')
plt.xlabel('Ano')
plt.ylabel('Número de Usuários (milhões)')

# Exibir o gráfico
plt.grid(True)
plt.show()

# Somar o número de usuários em todo o mundo por ano
world_data = dados.groupby('Year')['Users'].sum().reset_index()

# Criar o gráfico de evolução de usuários no mundo
plt.figure(figsize=(10,6))
plt.plot(world_data['Year'], world_data['Users'], marker='o', linestyle='-', color='g')

# Adicionar título e rótulos
plt.title('Evolução do Número de Usuários de Internet no Mundo')
plt.xlabel('Ano')
plt.ylabel('Número de Usuários (milhões)')

# Exibir o gráfico
plt.grid(True)
plt.show()

# Somar o número de usuários por continente e ano
continent_data = dados.groupby(['Continent', 'Year'])['Users'].sum().reset_index()

# Criar o gráfico de linhas para cada continente
plt.figure(figsize=(10,6))
sns.lineplot(data=continent_data, x='Year', y='Users', hue='Continent', marker='o')

# Adicionar título e rótulos
plt.title('Evolução do Número de Usuários de Internet por Continente')
plt.xlabel('Ano')
plt.ylabel('Número de Usuários (milhões)')

# Exibir o gráfico
plt.grid(True)
plt.show()

# Definir os países de interesse
paises_interesse = ['Brazil', 'United States', 'India', 'China', 'Germany']

# Filtrar os dados para esses países
country_data = dados[dados['Entity'].isin(paises_interesse)]

# Criar o gráfico de evolução para cada país
plt.figure(figsize=(10,6))
sns.lineplot(data=country_data, x='Year', y='Users', hue='Entity', marker='o')

# Adicionar título e rótulos
plt.title('Evolução do Número de Usuários de Internet por País')
plt.xlabel('Ano')
plt.ylabel('Número de Usuários (milhões)')

# Exibir o gráfico
plt.grid(True)
plt.show()

#MAPA COROPLÉTICO

#carregando arquivos do PC
from google.colab import files
uploaded = files.upload()

usuarios = pd.read_csv('4747-esi-semana-10-usuarios-populacao-por-pais-2021.csv')

#visualizando o começo do dataframe
usuarios.head()

#carregando arquivos do PC
from google.colab import files
uploaded = files.upload()

#carregando o arquivo com o formato dos países
mundo = gpd.read_file('World_Countries_Generalized (1).zip')

mundo.plot()

mundo.head()

#criando um simples mapa no folium
def criar_mapa():
  fmap = folium.Map(location=[0.0, 0.0], tiles="OpenStreetMap", zoom_start=2)
  return fmap

#juntando os dados em um novo dataframe
usuarios_por_pais = pd.merge(mundo,usuarios,left_on='ISO',right_on='code',how='left',sort=True)
usuarios_por_pais.head()

len(usuarios_por_pais)

#criando a coluna do percentual de usuarios de internet por pais
usuarios_por_pais['percentual_usuarios'] = usuarios_por_pais['internet_users']/usuarios_por_pais['population_2021']

#mapa coropletico com o percentual de usuarios de internet por pais
def plot_coropletico(fmap):
  choropleth_paises = folium.Choropleth(
      geo_data=usuarios_por_pais,
      data=usuarios_por_pais,
      columns=['ISO','percentual_usuarios'],
      key_on='feature.properties.ISO',
      legend_name='Usuarios de Internet (2021)',
      fill_color = 'YlGnBu'
  ).add_to(fmap)

  choropleth_paises.geojson.add_child(
      folium.features.GeoJsonTooltip(['COUNTRY','percentual_usuarios'])
  )
  return fmap

mapa = criar_mapa()

plot_coropletico(mapa)

